package VG;

import Vista.*;
import Modelo.Cuadrillas;
import Modelo.Trabajadores;
import controlador.ConsultasCuadrillas;
import controlador.ConsultasMYSQL;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cristoffer
 */
public class GCuadrillas extends javax.swing.JPanel {
   
	private static String nombre;
        private static int codigo;
        private ArrayList<Cuadrillas> listaCuadrilla=new ArrayList<Cuadrillas>();
    private DefaultTableModel modeloTabla=new DefaultTableModel();
    ConsultasMYSQL consultas1=new ConsultasMYSQL();
    ConsultasCuadrillas consultas=new ConsultasCuadrillas();
    public GCuadrillas() {         
        comprobarCuadrillas();
        agregarModeloTabla();
        initComponents();
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtCodigo = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        cajaCodigo = new javax.swing.JTextField();
        cajaNombre = new javax.swing.JTextField();
        btnoIngresar = new javax.swing.JButton();
        btnoBuscar = new javax.swing.JButton();
        btnobORRAR = new javax.swing.JButton();
        btnoLimpiar = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 0));

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("GESTION DE LAS CUADRILLAS");

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable1.setModel(modeloTabla);
        jScrollPane1.setViewportView(jTable1);

        txtCodigo.setBackground(new java.awt.Color(0, 0, 0));
        txtCodigo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigo.setText("Codigo");

        txtNombre.setBackground(new java.awt.Color(0, 0, 0));
        txtNombre.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setText("Nombre");

        btnoIngresar.setBackground(new java.awt.Color(0, 0, 0));
        btnoIngresar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnoIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnoIngresar.setText("Crear");
        btnoIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoIngresarActionPerformed(evt);
            }
        });

        btnoBuscar.setBackground(new java.awt.Color(0, 0, 0));
        btnoBuscar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnoBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnoBuscar.setText("Buscar");
        btnoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoBuscarActionPerformed(evt);
            }
        });

        btnobORRAR.setBackground(new java.awt.Color(0, 0, 0));
        btnobORRAR.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnobORRAR.setForeground(new java.awt.Color(255, 255, 255));
        btnobORRAR.setText("Borrar");
        btnobORRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnobORRARActionPerformed(evt);
            }
        });

        btnoLimpiar.setBackground(new java.awt.Color(0, 0, 0));
        btnoLimpiar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnoLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnoLimpiar.setText("Limpiar");
        btnoLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCodigo)
                            .addComponent(btnoLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnobORRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cajaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNombre)
                                .addGap(60, 60, 60)
                                .addComponent(cajaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnoIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(btnoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre)
                    .addComponent(cajaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigo))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnoLimpiar)
                    .addComponent(btnobORRAR)
                    .addComponent(btnoIngresar)
                    .addComponent(btnoBuscar))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnoIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoIngresarActionPerformed

        String cod=cajaCodigo.getText();
        codigo=Integer.parseInt(cod);
        nombre=cajaNombre.getText();

        if(  consultas.InsertarCuadrillas(codigo, nombre)==true){
            JOptionPane.showMessageDialog(null, "Se ha guardado los datos");
            //agregarCuadrilla();
        }

    }//GEN-LAST:event_btnoIngresarActionPerformed

    private void btnoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoBuscarActionPerformed
        String cod=cajaCodigo.getText();
        codigo=Integer.parseInt(cod);
        Cuadrillas c=consultas.buscarCuadrilla(codigo);
        if(c==null){
            JOptionPane.showMessageDialog(null, "Cuadrilla no registrada");
        }else{
            cajaNombre.setText(c.getNombreCuadrilla());
        }
    }//GEN-LAST:event_btnoBuscarActionPerformed

    private void btnobORRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnobORRARActionPerformed
        String cod=cajaCodigo.getText();
        codigo=Integer.parseInt(cod);
        if( consultas.borraCuadrilla(codigo)==true){
            JOptionPane.showMessageDialog(null, "Se ha borrado la cuadrilla");
            //        agregarCuadrilla();
        }
    }//GEN-LAST:event_btnobORRARActionPerformed

    private void btnoLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoLimpiarActionPerformed
        cajaCodigo.setText("");
        cajaNombre.setText("");
    }//GEN-LAST:event_btnoLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnoBuscar;
    private javax.swing.JButton btnoIngresar;
    private javax.swing.JButton btnoLimpiar;
    private javax.swing.JButton btnobORRAR;
    private javax.swing.JTextField cajaCodigo;
    private javax.swing.JTextField cajaNombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel txtCodigo;
    private javax.swing.JLabel txtNombre;
    // End of variables declaration//GEN-END:variables

    /**
     * Sacamos todas las cuadrillas de nuestra BD
     */    
      private void comprobarCuadrillas(){
        listaCuadrilla=consultas1.comprobarCuadrillas();
        
        
    }
      /**
       * Agregamos las cuadrillas de nuestro array list a nuetra tabla
       */
      /*
     private void agregarCuadrilla(){
      for (Cuadrillas c : listaCuadrilla) {
            String poda;
            int cant=consultas1.obtenerCantidadPersonas(c.getCodigoCuadrilla());            
         String cantidad=String.valueOf(cant);
            
       int cod_Trabajador=c.getCodigoCuadrilla();
        String codigo=String.valueOf(cod_Trabajador);
        nombre=c.getNombreCuadrilla();
        String[] jornal={codigo,nombre,cantidad};
        modeloTabla.addRow(jornal);
        }      
     } */ 
     
      
      
      
      /**
       * Agregamos los registros de nuestro array list a la cuadrilla
       */     
       private void agregarModeloTabla(){
        
        modeloTabla.addColumn("CodCuadrilla");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Cantidad de Personas");
        
        for (Cuadrillas c : listaCuadrilla) {
            
         int cant=consultas1.obtenerCantidadPersonas(c.getCodigoCuadrilla());            
         String cantidad=String.valueOf(cant);
       int cod_Trabajador=c.getCodigoCuadrilla();
        String codigo=String.valueOf(cod_Trabajador);
        nombre=c.getNombreCuadrilla();
        String[] jornal={codigo,nombre,cantidad};
        modeloTabla.addRow(jornal);
        }    
        
     
    }

}
