/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import controlador.ConsultasMYSQL;
import controlador.Mensajes_Error;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristoffer
 */
public class AccessoAlSistema extends javax.swing.JFrame implements Mensajes_Error {

    ConsultasMYSQL consultas = new ConsultasMYSQL();

    /**
     * Creates new form VentanaIngreso
     */
    public AccessoAlSistema() {
        iniciarVentana();
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.jpg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        etiquetaSistem = new javax.swing.JLabel();
        etiCod = new javax.swing.JLabel();
        etiNom = new javax.swing.JLabel();
        cajaNombre = new javax.swing.JTextField();
        cajaCod = new javax.swing.JTextField();
        btnoVolver = new javax.swing.JButton();
        btnoIngresar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panel.setBackground(new java.awt.Color(51, 153, 0));
        panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        etiquetaSistem.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaSistem.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        etiquetaSistem.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaSistem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaSistem.setText("ACCESO AL SISTEMA");

        etiCod.setBackground(new java.awt.Color(255, 255, 255));
        etiCod.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiCod.setForeground(new java.awt.Color(255, 255, 255));
        etiCod.setText("COD_TRABAJADOR");

        etiNom.setBackground(new java.awt.Color(255, 255, 255));
        etiNom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiNom.setForeground(new java.awt.Color(255, 255, 255));
        etiNom.setText("NOMBRE \nDE \nENCARGADO");

        cajaNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        cajaCod.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        btnoVolver.setBackground(new java.awt.Color(0, 0, 0));
        btnoVolver.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnoVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnoVolver.setText("Volver");
        btnoVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoVolverActionPerformed(evt);
            }
        });

        btnoIngresar.setBackground(new java.awt.Color(0, 0, 0));
        btnoIngresar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnoIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnoIngresar.setText("Ingresar");
        btnoIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoIngresarActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("EL EDÉN S.L");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(panelLayout.createSequentialGroup()
                                    .addComponent(etiNom)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cajaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(panelLayout.createSequentialGroup()
                                            .addComponent(btnoVolver)
                                            .addGap(106, 106, 106))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                                            .addComponent(etiCod)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cajaCod, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnoIngresar))))
                            .addComponent(etiquetaSistem, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetaSistem)
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiNom)
                    .addComponent(cajaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiCod)
                    .addComponent(cajaCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnoVolver)
                    .addComponent(btnoIngresar))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnoVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoVolverActionPerformed
        dispose();

        Fichar_Trabajadores vft = new Fichar_Trabajadores();
        vft.setVisible(true);

    }//GEN-LAST:event_btnoVolverActionPerformed

    private void btnoIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoIngresarActionPerformed
        boolean validos = true;
        String nombre = cajaNombre.getText();
        String valor = cajaCod.getText();
        try {
            int codigo = Integer.parseInt(valor);

            if ("".equals(nombre) && "".equals(valor)) {
                validos = false;
            }
            if (validos == true) {
                if (consultas.validardatos(nombre, codigo) == true) {
                    VentanaTareas vt = new VentanaTareas();
                    vt.setVisible(true);
                    dispose();

                } else {
                    JOptionPane.showMessageDialog(null, Datos_NO_VALIDOS,
                        TituloError, JOptionPane.ERROR_MESSAGE);                                        
                }
            } else {
                JOptionPane.showMessageDialog(null, Datos_NO_VALIDOS,
                        TituloError, JOptionPane.ERROR_MESSAGE);                    
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, Datos_NO_VALIDOS,
                        TituloError, JOptionPane.ERROR_MESSAGE);                    
        }

    }//GEN-LAST:event_btnoIngresarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnoIngresar;
    private javax.swing.JButton btnoVolver;
    private javax.swing.JTextField cajaCod;
    private javax.swing.JTextField cajaNombre;
    private javax.swing.JLabel etiCod;
    private javax.swing.JLabel etiNom;
    private javax.swing.JLabel etiquetaSistem;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
    private void iniciarVentana() {
        setSize(400, 400);
        setTitle("Fichar Trabajadores");
        setLocationRelativeTo(null);
        setLayout(null);
        this.setResizable(false);
        setDefaultCloseOperation(EXIT_ON_CLOSE);

    }
}
