/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import controlador.ConsultasMYSQL;
import controlador.Mensajes_Error;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristoffer
 */
public class Fichar_Trabajadores extends javax.swing.JFrame implements Mensajes_Error {

    ConsultasMYSQL consultas = new ConsultasMYSQL();

    /**
     * Creates new form VentanaFicharTrabajadores
     */
    public Fichar_Trabajadores() {
        iniciarVentana();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.jpg")).getImage());
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        cajaCodigo = new javax.swing.JTextField();
        etCodigo = new javax.swing.JLabel();
        radioButonFechaEntrada = new javax.swing.JRadioButton();
        radioButonFechaSalida = new javax.swing.JRadioButton();
        botonFichar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnoAccesoEncargado = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnoCerrar = new javax.swing.JButton();
        btnoAccesoPerito = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        cajaCodigo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cajaCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaCodigoActionPerformed(evt);
            }
        });

        etCodigo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etCodigo.setForeground(new java.awt.Color(255, 255, 255));
        etCodigo.setText("Codigo");

        buttonGroup1.add(radioButonFechaEntrada);
        radioButonFechaEntrada.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        radioButonFechaEntrada.setForeground(new java.awt.Color(255, 255, 255));
        radioButonFechaEntrada.setText("H/ENTRADA");

        buttonGroup1.add(radioButonFechaSalida);
        radioButonFechaSalida.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        radioButonFechaSalida.setForeground(new java.awt.Color(255, 255, 255));
        radioButonFechaSalida.setText("H/SALIDA");

        botonFichar.setBackground(new java.awt.Color(0, 0, 0));
        botonFichar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonFichar.setForeground(new java.awt.Color(255, 255, 255));
        botonFichar.setText("Fichar");
        botonFichar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFicharActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FICHAR");

        btnoAccesoEncargado.setBackground(new java.awt.Color(0, 0, 0));
        btnoAccesoEncargado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnoAccesoEncargado.setForeground(new java.awt.Color(255, 255, 255));
        btnoAccesoEncargado.setText("ENCARGADO");
        btnoAccesoEncargado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoAccesoEncargadoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("EL EDÉN S.L");

        btnoCerrar.setBackground(new java.awt.Color(0, 0, 0));
        btnoCerrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnoCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnoCerrar.setText("CERRAR");
        btnoCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoCerrarActionPerformed(evt);
            }
        });

        btnoAccesoPerito.setBackground(new java.awt.Color(0, 0, 0));
        btnoAccesoPerito.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnoAccesoPerito.setForeground(new java.awt.Color(255, 255, 255));
        btnoAccesoPerito.setText("PERITO");
        btnoAccesoPerito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoAccesoPeritoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(radioButonFechaSalida))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(etCodigo)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cajaCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                            .addComponent(radioButonFechaEntrada)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnoCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnoAccesoEncargado))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(botonFichar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnoAccesoPerito, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))))))
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButonFechaSalida)
                    .addComponent(radioButonFechaEntrada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etCodigo))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonFichar)
                    .addComponent(btnoCerrar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnoAccesoEncargado)
                    .addComponent(btnoAccesoPerito))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Se nos abre la ventana de acceso al sistema solo para encargados
     *
     * @param evt
     */
    private void btnoAccesoEncargadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoAccesoEncargadoActionPerformed
        AccessoAlSistema vi = new AccessoAlSistema();
        vi.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnoAccesoEncargadoActionPerformed

    /**
     * Con este metodo el codigo introducido se registra la con la salida o
     * entrada del trabajo
     *
     * @param evt
     */
    private void botonFicharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFicharActionPerformed
        try {
            String cod = cajaCodigo.getText();

            int codigo = Integer.parseInt(cod);
            if (radioButonFechaEntrada.isSelected()) {
                if (consultas.existeTrabajador(codigo) == true) {
                    if (consultas.trabajadorDuplicado(codigo) == true) {
                        consultas.FicharTrabajadorEntrada(codigo);
                        cajaCodigo.setText("");
                    } else {
                        
                        JOptionPane.showMessageDialog(null, Fichaje_Duplicado,
                        TituloError, JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, Codigo_No_Registrado,
                        TituloError, JOptionPane.ERROR_MESSAGE);                    
                }
            } else if (radioButonFechaSalida.isSelected()) {
                consultas.FicharTrabajadorSalida(codigo);
                cajaCodigo.setText("");

            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, Codigo_No_Valido,
                        TituloError, JOptionPane.ERROR_MESSAGE);                    
         
        }


    }//GEN-LAST:event_botonFicharActionPerformed

    private void cajaCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaCodigoActionPerformed

    private void btnoCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnoCerrarActionPerformed

    private void btnoAccesoPeritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoAccesoPeritoActionPerformed
        LoginPeritos l = new LoginPeritos();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnoAccesoPeritoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fichar_Trabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fichar_Trabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fichar_Trabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fichar_Trabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fichar_Trabajadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonFichar;
    private javax.swing.JButton btnoAccesoEncargado;
    private javax.swing.JButton btnoAccesoPerito;
    private javax.swing.JButton btnoCerrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cajaCodigo;
    private javax.swing.JLabel etCodigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radioButonFechaEntrada;
    private javax.swing.JRadioButton radioButonFechaSalida;
    // End of variables declaration//GEN-END:variables

    /**
     * Iniciamos la ventana
     */
    private void iniciarVentana() {
        setSize(400, 400);
        setTitle("Fichar Trabajadores");
        setLocationRelativeTo(null);
        setLayout(null);
        this.setResizable(false);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }
}
