/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Vista.*;
import Modelo.Cuadrillas;
import Modelo.Trabajadores;
import Modelo.Tractor;
import Modelo.Tractorista;
import controlador.ConsultasCuadrillas;
import controlador.ConsultasMYSQL;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cristoffer
 */
public class Gestion_Tractor_Tractorista extends javax.swing.JFrame {
        
	private static String nombre;
        private static int codigo;
        private ArrayList<Tractor> listaTractores=new ArrayList<Tractor>();
        private ArrayList<Tractorista> listaTractorista=new ArrayList<Tractorista>();
        private DefaultTableModel modeloTabla=new DefaultTableModel();        
        private DefaultComboBoxModel modeloTractor=new DefaultComboBoxModel();        
        private DefaultComboBoxModel modeloTractorista=new DefaultComboBoxModel();        
         ConsultasMYSQL consultas1=new ConsultasMYSQL();
         ConsultasCuadrillas consultas=new ConsultasCuadrillas();
    
         public Gestion_Tractor_Tractorista() {
        
        comprobarTractores();
        comprobarTractorista();
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.jpg")).getImage());
        jcomboTractores.addItem("Lista de Tractores");
        jcomboTractoristas.addItem("Lista de Tractoristas");
        agregarTractores_Tractorista();
        llenarComboBoxTractor();
        llenarComboBoxTractorista();
             setLocationRelativeTo(null);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtCodigo = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jcomboTractores = new javax.swing.JComboBox<>();
        jcomboTractoristas = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        btnoCerrar = new javax.swing.JButton();
        btnoAsignar = new javax.swing.JButton();
        btnoLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Asignacion de tractores");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("ASIGNACION TRACTOR-TRACTORISTA");

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable1.setModel(modeloTabla);
        jScrollPane1.setViewportView(jTable1);

        txtCodigo.setBackground(new java.awt.Color(0, 0, 0));
        txtCodigo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigo.setText("Tractores");

        txtNombre.setBackground(new java.awt.Color(0, 0, 0));
        txtNombre.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setText("Tractorista");

        jcomboTractores.setModel(modeloTractor);

        jcomboTractoristas.setModel(modeloTractorista);

        btnoCerrar.setBackground(new java.awt.Color(0, 0, 0));
        btnoCerrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnoCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnoCerrar.setText("Cerrar");
        btnoCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoCerrarActionPerformed(evt);
            }
        });

        btnoAsignar.setBackground(new java.awt.Color(0, 0, 0));
        btnoAsignar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnoAsignar.setForeground(new java.awt.Color(255, 255, 255));
        btnoAsignar.setText("Asignar");

        btnoLimpiar.setBackground(new java.awt.Color(0, 0, 0));
        btnoLimpiar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnoLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnoLimpiar.setText("Limpiar");
        btnoLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcomboTractores, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcomboTractoristas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnoAsignar)
                                .addGap(137, 137, 137)
                                .addComponent(btnoCerrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnoLimpiar)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo)
                    .addComponent(txtNombre)
                    .addComponent(jcomboTractores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcomboTractoristas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnoCerrar)
                    .addComponent(btnoAsignar)
                    .addComponent(btnoLimpiar))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Con este metodo Cerramos la ventana
 * @param evt 
 */
    private void btnoCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoCerrarActionPerformed
VentanaTareas vt=new VentanaTareas();
vt.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnoCerrarActionPerformed
/**
 * Con este metodo limpiamos los campos despues de hacer alguna tarea
 * @param evt 
 */
    private void btnoLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoLimpiarActionPerformed
jcomboTractores.setSelectedIndex(0);
jcomboTractoristas.setSelectedIndex(0);
    }//GEN-LAST:event_btnoLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_Tractor_Tractorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_Tractor_Tractorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_Tractor_Tractorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_Tractor_Tractorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion_Tractor_Tractorista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnoAsignar;
    private javax.swing.JButton btnoCerrar;
    private javax.swing.JButton btnoLimpiar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jcomboTractores;
    private javax.swing.JComboBox<String> jcomboTractoristas;
    private javax.swing.JLabel txtCodigo;
    private javax.swing.JLabel txtNombre;
    // End of variables declaration//GEN-END:variables

     /**
 * * Obtenemos una lista de tractores
 */
      private void comprobarTractores(){
        listaTractores=consultas1.comprobarTractores();        
    }
      /**
 * * Obtenemos una lista de tractoristas
 */
      private void comprobarTractorista(){
        listaTractorista=consultas1.comprobarTractoristas();        
    }
      
       /**
       * Agregamos a la tabla los tractores asignados de nuestra BD
       */    
     private void agregarTractores_Tractorista(){
        modeloTabla.addColumn("Cod_Tractor");
        modeloTabla.addColumn("Tractorista");
        modeloTabla.addColumn("Fecha");
        modeloTabla.addRow(consultas1.obtenertractresAsignados());
        }      
/**
 * * Llenamos el combobox con nuestros tractores
 */
private void llenarComboBoxTractor() {
        for (Tractor listaTractore : listaTractores) {
            modeloTractor.addElement(listaTractore.mostrarinformacion());
            
        }
    }
/**
 * * Llenamos el combobox con nuestros tractoristas
 */
    private void llenarComboBoxTractorista() {
        for (Tractorista tractorista : listaTractorista) {
            modeloTractorista.addElement(tractorista.obtenerdatos());
        }
            
            
        }
    
     }  
     
   

