/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.H_CONECTADA;
import Modelo.Tractor;
import controlador.ConsultasMYSQL;
import controlador.ConsultasTractor;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cristoffer
 */
public class GestionarHerramientas extends javax.swing.JFrame {

    private static int codtrabaj;
    private static String matricula;
    private DefaultComboBoxModel modelo = new DefaultComboBoxModel<>();
    private ArrayList<H_CONECTADA> listaHerramientas = new ArrayList<H_CONECTADA>();
    private DefaultTableModel modeloTabla = new DefaultTableModel();
    private static ArrayList<Tractor> listaTractor = new ArrayList<>();
    ConsultasMYSQL consultas1 = new ConsultasMYSQL();
    ConsultasTractor consulta = new ConsultasTractor();
    private String Columnas[] = {"Codigo de tractor", "Matricula", "Herramienta"};

    public GestionarHerramientas() {
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.jpg")).getImage());
        //iniciarFormulario();
        initComponents();
        //Metodos Para El insertar
        comprobarHerramientas();
        jcomboHerramienta.addItem("Selecciona una herramienta");
        llenarModeloComboBox();
        //Metodo Para actualizar
        asignarColumnas();
        actualizar_Tabla();

        setLocationRelativeTo(null);

    }

    private void llenarModeloComboBox() {

        for (H_CONECTADA h : listaHerramientas) {
            modelo.addElement(h);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        etiquetaCodigo = new javax.swing.JLabel();
        cajaCodigo = new javax.swing.JTextField();
        etiquetaNombre = new javax.swing.JLabel();
        etiquetaCuadrilla = new javax.swing.JLabel();
        cajaMatricula = new javax.swing.JTextField();
        btnoInsertar = new javax.swing.JButton();
        btnoModificar = new javax.swing.JButton();
        btnoBuscar = new javax.swing.JButton();
        btnoBaja = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jcomboHerramienta = new javax.swing.JComboBox<>();
        btnoCerrar = new javax.swing.JButton();
        btnoLimpiar = new javax.swing.JButton();
        etiquetaCodigo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion Herramientas");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Gestion de Herramientas");

        etiquetaCodigo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiquetaCodigo.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaCodigo.setText("CodigoTractor");

        cajaCodigo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cajaCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaCodigoActionPerformed(evt);
            }
        });

        etiquetaNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiquetaNombre.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaNombre.setText("Matricula");

        etiquetaCuadrilla.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiquetaCuadrilla.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaCuadrilla.setText("Herramienta");

        cajaMatricula.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cajaMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaMatriculaActionPerformed(evt);
            }
        });

        btnoInsertar.setBackground(new java.awt.Color(0, 0, 0));
        btnoInsertar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnoInsertar.setForeground(new java.awt.Color(255, 255, 255));
        btnoInsertar.setText("Insertar");
        btnoInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoInsertarActionPerformed(evt);
            }
        });

        btnoModificar.setBackground(new java.awt.Color(0, 0, 0));
        btnoModificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnoModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnoModificar.setText("Modificar");
        btnoModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoModificarActionPerformed(evt);
            }
        });

        btnoBuscar.setBackground(new java.awt.Color(0, 0, 0));
        btnoBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnoBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnoBuscar.setText("Buscar");
        btnoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoBuscarActionPerformed(evt);
            }
        });

        btnoBaja.setBackground(new java.awt.Color(0, 0, 0));
        btnoBaja.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnoBaja.setForeground(new java.awt.Color(255, 255, 255));
        btnoBaja.setText("Baja");
        btnoBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoBajaActionPerformed(evt);
            }
        });

        jTable1.setModel(modeloTabla);
        ListSelectionListener oyenteSeleccion=new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent e){
                if(e.getValueIsAdjusting()){
                    int filaSeleccionada=jTable1.getSelectedRow();
                    String codigo=(String) modeloTabla.getValueAt(filaSeleccionada, 0);
                    String nombre=(String) modeloTabla.getValueAt(filaSeleccionada, 1);
                    String apellido=(String) modeloTabla.getValueAt(filaSeleccionada, 2);
                    String telefono=(String) modeloTabla.getValueAt(filaSeleccionada, 3);

                    cajaCodigo.setText(codigo);
                    cajaMatricula.setText(nombre);

                }

            }
        };
        jTable1.getSelectionModel().addListSelectionListener(oyenteSeleccion);
        jScrollPane1.setViewportView(jTable1);

        jcomboHerramienta.setModel(modelo);

        btnoCerrar.setBackground(new java.awt.Color(0, 0, 0));
        btnoCerrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnoCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnoCerrar.setText("Cerrar");
        btnoCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoCerrarActionPerformed(evt);
            }
        });

        btnoLimpiar.setBackground(new java.awt.Color(0, 0, 0));
        btnoLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnoLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnoLimpiar.setText("Limpiar");
        btnoLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoLimpiarActionPerformed(evt);
            }
        });

        etiquetaCodigo1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiquetaCodigo1.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaCodigo1.setText("LISTA DE TRACTORES ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(etiquetaCodigo)
                                .addGap(14, 14, 14)
                                .addComponent(cajaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(etiquetaNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cajaMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaCodigo1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnoInsertar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnoModificar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnoBuscar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnoCerrar))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(etiquetaCuadrilla)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jcomboHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnoBaja)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnoLimpiar)))
                        .addGap(0, 17, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cajaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(etiquetaCodigo)
                        .addComponent(etiquetaNombre)
                        .addComponent(cajaMatricula)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcomboHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaCuadrilla))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnoInsertar)
                    .addComponent(btnoModificar)
                    .addComponent(btnoBuscar)
                    .addComponent(btnoCerrar)
                    .addComponent(btnoBaja)
                    .addComponent(btnoLimpiar))
                .addGap(19, 19, 19)
                .addComponent(etiquetaCodigo1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cajaCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaCodigoActionPerformed

    private void cajaMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaMatriculaActionPerformed

    private void btnoInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoInsertarActionPerformed

        int herramienta = 0;
        String codigo = cajaCodigo.getText();
        codtrabaj = Integer.parseInt(codigo);
        matricula = cajaMatricula.getText();
        String cua = (String) jcomboHerramienta.getSelectedItem().toString();
        for (H_CONECTADA listaHerramienta : listaHerramientas) {
            if (cua.equals(listaHerramienta.toString())) {
                herramienta = listaHerramienta.getId();
            }
        }

        consulta.InsertarTractor(codtrabaj, matricula, herramienta);
        actualizar_Tabla();


    }//GEN-LAST:event_btnoInsertarActionPerformed

    private void btnoModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoModificarActionPerformed
        int herramienta = 0;
        String codigo = cajaCodigo.getText();
        codtrabaj = Integer.parseInt(codigo);
        matricula = cajaMatricula.getText();
        String cua = (String) jcomboHerramienta.getSelectedItem().toString();
        for (H_CONECTADA listaHerramienta : listaHerramientas) {
            if (cua.equals(listaHerramienta.toString())) {
                herramienta = listaHerramienta.getId();
            }
        }

        consulta.actualizarTractor(codtrabaj, matricula, herramienta);
        actualizar_Tabla();

    }//GEN-LAST:event_btnoModificarActionPerformed

    private void btnoBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoBajaActionPerformed
        String codigo = cajaCodigo.getText();
        int Cod_Tractor = Integer.parseInt(codigo);
        consulta.BorrarTractor(Cod_Tractor);
        actualizar_Tabla();

    }//GEN-LAST:event_btnoBajaActionPerformed

    private void btnoCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoCerrarActionPerformed
        VentanaTareas vt = new VentanaTareas();
        vt.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnoCerrarActionPerformed

    private void btnoLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoLimpiarActionPerformed
        cajaCodigo.setText("");
        cajaMatricula.setText("");
        jcomboHerramienta.setSelectedIndex(0);
    }//GEN-LAST:event_btnoLimpiarActionPerformed

    private void btnoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoBuscarActionPerformed

        String codigo = cajaCodigo.getText();
        codtrabaj = Integer.parseInt(codigo);

        for (Tractor tractor : listaTractor) {
            if (tractor.getCod_tractor() == codtrabaj) {
                //int codigoHerramienta=tractor.getHerramienta().getId();
                cajaCodigo.setText(codigo);
                cajaMatricula.setText(tractor.getMatricula());

            }

        }


    }//GEN-LAST:event_btnoBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarHerramientas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarHerramientas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarHerramientas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarHerramientas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarHerramientas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnoBaja;
    private javax.swing.JButton btnoBuscar;
    private javax.swing.JButton btnoCerrar;
    private javax.swing.JButton btnoInsertar;
    private javax.swing.JButton btnoLimpiar;
    private javax.swing.JButton btnoModificar;
    private javax.swing.JTextField cajaCodigo;
    private javax.swing.JTextField cajaMatricula;
    private javax.swing.JLabel etiquetaCodigo;
    private javax.swing.JLabel etiquetaCodigo1;
    private javax.swing.JLabel etiquetaCuadrilla;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jcomboHerramienta;
    // End of variables declaration//GEN-END:variables

    /**
     * Obtenemos en un array list todas las herremaientas disponibles de nuestra
     * base de datos
     */
    private void comprobarHerramientas() {
        listaHerramientas = consultas1.comprobarHerramientas();
    }

    /**
     * Sacamos todos los tractores de nuestra BD
     */
    private void sacarTractoresBD() {
        listaTractor = consultas1.sacarTractores();

    }

    /**
     * Agregamos los registros que hemos obtenido de nuestra BD a nuestra tabla
     */
    private void agregarModeloTabla() {
        LimpiarTabla();

        for (Tractor tractor : listaTractor) {
            int cod = tractor.getCod_tractor();
            String codigo = String.valueOf(cod);
            String matricula = tractor.getMatricula();
            String herramienta = tractor.getHerramienta().getNombre();
            String[] tract = {codigo, matricula, herramienta};
            modeloTabla.addRow(tract);
        }

    }

    /**
     * Cada vez que hagamos una operacion se nos limpiara la tabla
     */
    public void LimpiarTabla() {
        int lon = modeloTabla.getRowCount();
        for (int i = 0; i < lon; i++) {
            modeloTabla.removeRow(0);

        }
    }

    /**
     * Asiganmos el nombre de las columnas a nuestra tabal
     */
    private void asignarColumnas() {
        for (int i = 0; i < Columnas.length; i++) {
            modeloTabla.addColumn(Columnas[i]);
        }
    }

    /**
     * Metodo que nos actualiza la tabla de los tractores
     */
    private void actualizar_Tabla() {
        sacarTractoresBD();
        agregarModeloTabla();
    }
}
