/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Cuadrillas;
import Modelo.Jornaleros;
import Modelo.Tractorista;
import controlador.ConsultasMYSQL;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cristoffer
 */
public class ListarTrabajadoresPorCuadrillas extends javax.swing.JFrame {

    /**
     * Creates new form VentanaConsultarTrabajadoresPorCuadrilla
     */
    //private static Connection conexion;
    private DefaultComboBoxModel modelo = new DefaultComboBoxModel<>();
    private DefaultComboBoxModel modeloTractorista = new DefaultComboBoxModel<>();
    private DefaultTableModel modeloTabla = new DefaultTableModel();
    private ArrayList<Cuadrillas> listaCuadrilla = new ArrayList<Cuadrillas>();
    private ConsultasMYSQL consultas = new ConsultasMYSQL();
    private String Columnas[] = {"Cod_Trabajador", "Nombre", "Apellidos", "Telefono", "Podador", "Tipo"};

    public ListarTrabajadoresPorCuadrillas() {
        iniciarFormulario();
        obtenerCuadrillas();
        llenarModeloComboBox();
        asignarColumnas();
        initComponents();
    }

    private void iniciarFormulario() {
        setSize(400, 400);
        setTitle("Lista de Trabajadores Por cuadrilla");
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.jpg")).getImage());
        setLayout(null);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etiquetaManijero = new javax.swing.JLabel();
        etiquetaCuadrilla = new javax.swing.JLabel();
        cajaManijero = new javax.swing.JTextField();
        etiquetaTractorista = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaJornaleros = new javax.swing.JTable();
        etiquetaTrabajadores = new javax.swing.JLabel();
        btnoComprobar = new javax.swing.JButton();
        jcomboTractorista = new javax.swing.JComboBox<>();
        jcomboCuadrilla = new javax.swing.JComboBox<>();
        btnoVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consultar Trabajadores Cuadrilla");

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        etiquetaManijero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaManijero.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaManijero.setText("Manijero Asignado");

        etiquetaCuadrilla.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaCuadrilla.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaCuadrilla.setText("Cuadrilla");

        cajaManijero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaManijeroActionPerformed(evt);
            }
        });

        etiquetaTractorista.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaTractorista.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaTractorista.setText("Tractorista Asignado");

        tablaJornaleros.setModel(modeloTabla);
        jScrollPane1.setViewportView(tablaJornaleros);

        etiquetaTrabajadores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaTrabajadores.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaTrabajadores.setText("Jornaleros Asignados");

        btnoComprobar.setBackground(new java.awt.Color(0, 0, 0));
        btnoComprobar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnoComprobar.setForeground(new java.awt.Color(255, 255, 255));
        btnoComprobar.setText("Comprobar");
        btnoComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoComprobarActionPerformed(evt);
            }
        });

        jcomboTractorista.setModel(modeloTractorista);
        jcomboTractorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboTractoristaActionPerformed(evt);
            }
        });

        jcomboCuadrilla.setModel(modelo);
        jcomboCuadrilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboCuadrillaActionPerformed(evt);
            }
        });

        btnoVolver.setBackground(new java.awt.Color(0, 0, 0));
        btnoVolver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnoVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnoVolver.setText("Volver");
        btnoVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoVolverActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ConsultarTrabajadores por Cuadrilla");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cajaManijero, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiquetaManijero)
                                    .addComponent(jcomboCuadrilla, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnoComprobar)
                                    .addComponent(etiquetaTractorista))
                                .addGap(38, 38, 38))
                            .addComponent(jcomboTractorista, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaTrabajadores)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(etiquetaCuadrilla)))
                        .addGap(0, 388, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(btnoVolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(etiquetaCuadrilla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcomboCuadrilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnoComprobar))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaTractorista)
                    .addComponent(etiquetaManijero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaManijero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcomboTractorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetaTrabajadores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnoVolver)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cajaManijeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaManijeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaManijeroActionPerformed

    private void btnoComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoComprobarActionPerformed

        int valorintroducido = 0;
        LimpiarTabla();
        String cua = (String) jcomboCuadrilla.getSelectedItem().toString();
        for (Cuadrillas cuadrillas : listaCuadrilla) {
            if (cua.equals(cuadrillas.toString())) {
                valorintroducido = cuadrillas.getCodigoCuadrilla();
            }
        }
        for (Cuadrillas cuadrillas : listaCuadrilla) {
            if (cuadrillas.getCodigoCuadrilla() == valorintroducido) {
                cajaManijero.setText(cuadrillas.MostrarManijero());
                modeloTractorista.removeAllElements();
                obtenerTractoristas(cuadrillas);
                cargarJornalerosenTabla(cuadrillas);

            }

        }

    }//GEN-LAST:event_btnoComprobarActionPerformed

    private void jcomboCuadrillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboCuadrillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomboCuadrillaActionPerformed

    private void jcomboTractoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboTractoristaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomboTractoristaActionPerformed

    private void btnoVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoVolverActionPerformed
        VentanaTareas vt = new VentanaTareas();
        vt.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnoVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarTrabajadoresPorCuadrillas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarTrabajadoresPorCuadrillas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarTrabajadoresPorCuadrillas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarTrabajadoresPorCuadrillas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarTrabajadoresPorCuadrillas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnoComprobar;
    private javax.swing.JButton btnoVolver;
    private javax.swing.JTextField cajaManijero;
    private javax.swing.JLabel etiquetaCuadrilla;
    private javax.swing.JLabel etiquetaManijero;
    private javax.swing.JLabel etiquetaTrabajadores;
    private javax.swing.JLabel etiquetaTractorista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcomboCuadrilla;
    private javax.swing.JComboBox<String> jcomboTractorista;
    private javax.swing.JTable tablaJornaleros;
    // End of variables declaration//GEN-END:variables

    /**
     * Llenar el modelo con nuestras cuadrillas
     */
    private void llenarModeloComboBox() {

        for (Cuadrillas cuadrillas : listaCuadrilla) {
            //System.out.println(cuadrillas);
            modelo.addElement(cuadrillas);

        }
    }

    /**
     * Obtenemos las cuadrillas
     */
    private void obtenerCuadrillas() {
        listaCuadrilla = consultas.obtenerCuadrillas();

    }

    /**
     * Cargamos los trabajadores en la tabla
     */
    private void cargarJornalerosenTabla(Cuadrillas c) {

        for (Jornaleros jornaleros : c.getJornaleros()) {
            String poda;

            int cod_Trabajador = jornaleros.getCod_Trabajador();
            String codigo = String.valueOf(cod_Trabajador);
            int tlfn = jornaleros.getTelefono();
            String telefono = String.valueOf(tlfn);
            String nombre = jornaleros.getNombre();
            String apellidos = jornaleros.getApellidos();

            String tipo = jornaleros.getTipoTrabajador();

            boolean podador = jornaleros.isPodador();
            if (podador == false) {
                poda = "No";
            } else {
                poda = "Si";
            }

            String[] jornal = {codigo, nombre, apellidos, telefono, poda, tipo};
            modeloTabla.addRow(jornal);
        }

    }

    /**
     * Asignamos la columnas a la tabla
     */
    private void asignarColumnas() {
        for (int i = 0; i < Columnas.length; i++) {
            modeloTabla.addColumn(Columnas[i]);
        }
    }

    public void LimpiarTabla() {
        int lon = modeloTabla.getRowCount();
        for (int i = 0; i < lon; i++) {
            modeloTabla.removeRow(0);

        }
    }

    /**
     * Obtenemos los tractorista de la cuadrilla solicitada
     *
     * @param cuadrillas
     */
    public void obtenerTractoristas(Cuadrillas cuadrillas) {
        for (Tractorista tractorista : cuadrillas.getTractorista()) {
            modeloTractorista.addElement(tractorista);

        }
    }

}
