/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.DefaultComboBoxModel;
import Modelo.Trabajadores;
import Modelo.Jornaleros;
import controlador.ConsultasMYSQL;
import controlador.ConsultasMYSQL;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cristoffer
 */
public class ListarTrabajadores extends javax.swing.JFrame {

    private DefaultComboBoxModel<Jornaleros> modelo = new DefaultComboBoxModel<Jornaleros>();
    private DefaultTableModel modeloTabla = new DefaultTableModel();
    private static Connection conexion;
    private static ArrayList<Trabajadores> lista_trabajabadores;
    private static ConsultasMYSQL consultas = new ConsultasMYSQL();

    /**
     * Creates new form VentanaConsultarTrabajadores
     */
    public ListarTrabajadores() {
        iniciarFormulario();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.jpg")).getImage());
        llenarListaTrabajadores();
        agregarModeloTabla();
        initComponents();
    }

    private void iniciarFormulario() {
        setSize(400, 400);
        setTitle("Gestion de las Cuadrillas");
        setLocationRelativeTo(null);
        setLayout(null);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnvolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lista de Trabajadores");

        jTable1.setModel(modeloTabla);
        jScrollPane1.setViewportView(jTable1);

        btnvolver.setBackground(new java.awt.Color(0, 0, 0));
        btnvolver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnvolver.setForeground(new java.awt.Color(255, 255, 255));
        btnvolver.setText("Volver");
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(btnvolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnvolver))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        VentanaTareas vt = new VentanaTareas();
        vt.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnvolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnvolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
/**
     * Sacamos los trabajadores y lo guardamos en un arraylist
     */
    private void llenarListaTrabajadores() {
        lista_trabajabadores = consultas.sacarTrabajadoresdeBD();
    }

    /**
     * Agregamos las columnas y agregamos los valores a la tabla
     */
    private void agregarModeloTabla() {

        modeloTabla.addColumn("Cod_Trabajador");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Apellidos");
        modeloTabla.addColumn("Telefono");
        modeloTabla.addColumn("Cuadrilla");
        modeloTabla.addColumn("Podador");
        modeloTabla.addColumn("Tipo");

        for (Trabajadores trabajador : lista_trabajabadores) {
            String poda;

            int cod_Trabajador = trabajador.getCod_Trabajador();
            String codigo = String.valueOf(cod_Trabajador);
            int tlfn = trabajador.getTelefono();
            String telefono = String.valueOf(tlfn);
            String nombre = trabajador.getNombre();
            String apellidos = trabajador.getApellidos();
            int cuadrilla = trabajador.getCuadrilla();
            String grupo = String.valueOf(cuadrilla);
            String TipoTrabajador = trabajador.getTipoTrabajador();
            boolean podador = trabajador.isPodador();
            if (podador == false) {
                poda = "No";
            } else {
                poda = "Si";
            }
            String[] jornal = {codigo, nombre, apellidos, telefono, grupo, poda, TipoTrabajador};
            modeloTabla.addRow(jornal);
        }

    }

}
