/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import CrudWebservice.GestionInformes;
import Vista.LoginPeritos;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Informes;

/**
 *
 * @author Cristoffer
 */
public class VentanaCrud extends javax.swing.JFrame implements Mensajes {

    /**
     * Creates new form VentanaCrud1
     */
    public VentanaCrud() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/IMAGENES/icono_1.jpg")).getImage());
        setTitle(Titulo);
        setLocationRelativeTo(null);
    }

    public void obtenercodigo(String codigo) {
        String codigoPerito = codigo;
        cajaPerito.setText(codigoPerito);
        cajaPerito.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnoBuscar = new javax.swing.JButton();
        btnoIngresar = new javax.swing.JButton();
        btnoBorrar = new javax.swing.JButton();
        btnoModificar = new javax.swing.JButton();
        btnoLimpiar = new javax.swing.JButton();
        cajaPerito = new javax.swing.JTextField();
        cajaIdFruta = new javax.swing.JTextField();
        cajaAsunto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        cajaDescripcion = new javax.swing.JTextArea();
        cajaid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnoCerrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnoBuscar.setText("Buscar");
        btnoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoBuscarActionPerformed(evt);
            }
        });

        btnoIngresar.setText("Ingresar");
        btnoIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoIngresarActionPerformed(evt);
            }
        });

        btnoBorrar.setText("Borrar");
        btnoBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoBorrarActionPerformed(evt);
            }
        });

        btnoModificar.setText("Modificar");
        btnoModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoModificarActionPerformed(evt);
            }
        });

        btnoLimpiar.setText("Limpiar");
        btnoLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoLimpiarActionPerformed(evt);
            }
        });

        cajaDescripcion.setColumns(20);
        cajaDescripcion.setRows(5);
        jScrollPane1.setViewportView(cajaDescripcion);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("DESCRIPCION");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Asunto");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Fruta");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("PERITO");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("ID");

        jLabel6.setIcon(new javax.swing.ImageIcon("F:\\datos\\2ADAM\\ProgramasUsoClase\\NetBeans\\ProyectoFinal\\AFF\\src\\imagenes\\icono_1.jpg")); // NOI18N

        btnoCerrar.setText("Cerrar");
        btnoCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoCerrarActionPerformed(evt);
            }
        });

        jLabel7.setText("(introduzca 0 o 1)");

        jLabel8.setText("(rellenar en caso de buscar un informe o borrarlo)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnoLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnoCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cajaAsunto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                                    .addComponent(cajaIdFruta, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cajaPerito, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnoModificar)
                                    .addComponent(btnoBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cajaid, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnoIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cajaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnoIngresar))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cajaPerito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnoModificar))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaIdFruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnoBorrar))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnoBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnoLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnoCerrar)
                        .addGap(114, 114, 114))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnoIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoIngresarActionPerformed
        boolean datosvalidos = true;
        String codigo = cajaPerito.getText();
        String Fruta = cajaIdFruta.getText();
        String Asunto = cajaAsunto.getText();
        String descr = cajaDescripcion.getText();
        System.out.println("la fruta devuelve " + Fruta);
        if ("".equals(Fruta) || "".equals(Asunto) || "".equals(descr)) {
            datosvalidos = false;
        }

        if (datosvalidos == true) {

            if (GestionInformes.insertar(codigo, Fruta, Asunto, descr) == true) {
                JOptionPane.showMessageDialog(null, MensajeInsertarpositiva);
            } else {
                JOptionPane.showMessageDialog(null, MensajeInsertarnegativa);
            }
        } else {
            JOptionPane.showMessageDialog(null, DatosNOValidos);
        }
    }//GEN-LAST:event_btnoIngresarActionPerformed

    private void btnoModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoModificarActionPerformed
        boolean datosvalidos = true;
        String Id = cajaid.getText();
        String codigo = cajaPerito.getText();
        String Fruta = cajaIdFruta.getText();
        String Asunto = cajaAsunto.getText();
        String descr = cajaDescripcion.getText();

        if ("".equals(Id) || "".equals(Fruta) || "".equals(Asunto) || "".equals(descr)) {
            datosvalidos = false;
        }
        if (datosvalidos == true) {
            if (GestionInformes.modificar(Id, codigo, Fruta, Asunto, descr) == true) {
                JOptionPane.showMessageDialog(null, MensajeModificadopositiva);
            } else {
                JOptionPane.showMessageDialog(null, MensajeModificadonegativa);

            }
        } else {
            JOptionPane.showMessageDialog(null, DatosNOValidos);
        }
    }//GEN-LAST:event_btnoModificarActionPerformed

    private void btnoBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoBorrarActionPerformed
        String Id = cajaid.getText();
        boolean datosvalidos = true;

        if ("".equals(Id)) {
            datosvalidos = false;
        }
        if (datosvalidos == true) {
            if (GestionInformes.borrar(Id) == true) {
                JOptionPane.showMessageDialog(null, Mensajeborrarpositiva);
                cajaid.setText("");
                cajaIdFruta.setText("");
                cajaAsunto.setText("");
                cajaDescripcion.setText("");
            } else {
                JOptionPane.showMessageDialog(null, Mensajeborrarnegativa);
            }
        } else {
            JOptionPane.showMessageDialog(null, DatosNOValidos);
        }
    }//GEN-LAST:event_btnoBorrarActionPerformed

    private void btnoLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoLimpiarActionPerformed
        cajaid.setText("");
        cajaIdFruta.setText("");
        cajaAsunto.setText("");
        cajaDescripcion.setText("");
    }//GEN-LAST:event_btnoLimpiarActionPerformed

    private void btnoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoBuscarActionPerformed
        String Id = cajaid.getText();

        Informes info = GestionInformes.buscarRegistro(Id);
        if (info == null) {
            JOptionPane.showMessageDialog(null, ERRORBUSCAR);

        } else {
            cajaIdFruta.setText(info.getId_Fruta());
            cajaAsunto.setText(info.getAsunto());
            cajaDescripcion.setText(info.getDescripcion());
        }
    }//GEN-LAST:event_btnoBuscarActionPerformed

    private void btnoCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoCerrarActionPerformed
        LoginPeritos l = new LoginPeritos();
        l.setVisible(true);
        dispose();

    }//GEN-LAST:event_btnoCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnoBorrar;
    private javax.swing.JButton btnoBuscar;
    private javax.swing.JButton btnoCerrar;
    private javax.swing.JButton btnoIngresar;
    private javax.swing.JButton btnoLimpiar;
    private javax.swing.JButton btnoModificar;
    private javax.swing.JTextField cajaAsunto;
    private javax.swing.JTextArea cajaDescripcion;
    private javax.swing.JTextField cajaIdFruta;
    private javax.swing.JTextField cajaPerito;
    private javax.swing.JTextField cajaid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
